---
spring:
  profiles: cloud, default
  application:
    name: cloud-native-spring
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  main:
    allow-bean-definition-overriding: true


info: # add this section
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@



management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

